{% set name = "dolos" %}
{% set version = "10.19.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dolos-{{ version }}.tar.gz
  sha256: fc5fa6238fd9c8e3339bb7ebcb5ee67476c911f432a6d7f85a41091f3ab7346c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - ibapi
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dolos
  home: 'https://github.com/DolosIAB/dolos-iab'
  license: 'MIT'
  license_file: 'LICENSE.txt'

extra:
  recipe-maintainers:
    - dolos
